### ISSUE TITLE
Able to do "encoding: null" option in invoke/POST?

### ISSUE THREAD

**Issue by ghost** [austinfrey/node-openfaas#1]
In my telegram bot I need to send data to the functions with POST requests with the option `encoding: null`. Is it possible to use this option in this library?

If this works, my code will be greatly simplified. :+1:

**Comment by austinfrey** [comment]
Hey @ericstoekl you bet. Thanks for giving this a go! I'll be working on this more this week, but if you see anything else that could be tweaked be sure to reach out 👍 Osss lol

**Comment by austinfrey** [comment]
@ericstoekl merged my man! thanks again
